# version: '3'
# services:
#   postgres-db:
#     image: "postgres:12"
#     container_name: "node-gmp-db"
#     environment:
#       - POSTGRES_USER=node_gmp
#       - POSTGRES_PASSWORD=password123
#       - POSTGRES_DB=node_gmp
#     restart: always
#     ports:
#       - '5432:5432'

version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        volumes:
            - ./data/db:/data/db
        container_name: dkrcomp-mongo
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo_db
            - MONGO_INITDB_ROOT_PASSWORD=Password123
        image: mongo
        