
version: '3.9'
services:
    app:
        container_name: my_app
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_ENV: production
                restart: always
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: 'production'
            MONGO_URI: 'mongodb+srv://mongo_db:Password123@cluster0.nxzrh8i.mongodb.net/'
            REDIS_URL: redis://redis:6379
        depends_on:
            - mongo
            - redis
        networks:
            - my_network

    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - '27017:27017'
        volumes:
            - ./data/db:/data/db
        restart: always
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo_db
            - MONGO_INITDB_ROOT_PASSWORD=Password123
        networks:
            - my_network

    redis:
        container_name: redis
        image: redis:latest
        ports:
            - '6379:6379'
        volumes:
            - ./data/redis:/data/redis
        restart: always
        logging:
            options:
                max-size: 1g
        networks:
            - my_network

networks:
    my_network:

